"""Generate the permission matrix and state machine documents from the code.

Run after changing roles, permissions or state machines:

    docker compose run --rm --no-deps -v "$PWD:/repo" -w /app \
      --entrypoint python api scripts/generate_docs.py /repo/docs

Generating these rather than writing them by hand means the documents cannot drift from
the enforced behaviour.
"""

from __future__ import annotations

import sys
from datetime import UTC, datetime
from pathlib import Path

from app.domain.enums import Role
from app.domain.states import CASE_MACHINE, COMPLAINT_MACHINE, INSPECTION_MACHINE
from app.security.permissions import (
    HIERARCHY_ROLES,
    ROLE_PERMISSIONS,
    UNSCOPED_ROLES,
    Permission,
)

GENERATED_NOTE = "<!-- Generated by api/scripts/generate_docs.py. Edit the code, not this file. -->"

ROLE_SUMMARY: dict[str, str] = {
    "inspector": "Field officer. Opens inspections, captures evidence, reviews machine "
    "readings, runs the checks. Cannot record the final decision.",
    "reviewer": "Records the reasoned decision, issues reports, opens cases and issues "
    "notices. Cannot read the audit trail.",
    "controller": "Supervises a jurisdiction subtree. Everything a reviewer can do, plus "
    "closing matters, withdrawing reports and notices, and reading the audit trail.",
    "rule_admin": "Governs legal content. Authors, simulates, approves and activates rule "
    "versions. Has no access to evidence.",
    "admin": "Workspace administration. Accounts, roles, jurisdictions and sessions. "
    "Holds every permission.",
}


def permissions_document() -> str:
    lines: list[str] = [
        "# Roles, permissions and jurisdiction",
        "",
        GENERATED_NOTE,
        "",
        "Two independent gates guard every request, and both must pass.",
        "",
        "1. **Role permission** decides what kind of action an account may perform.",
        "2. **Jurisdiction scope** decides which records it may perform it on, and is",
        "   applied inside the SQL query rather than after loading.",
        "",
        "A reviewer holding `inspection.decide` still cannot decide an inspection in",
        "another jurisdiction. An out-of-scope record returns **404, not 403**, so a",
        "guessed identifier cannot confirm that a record exists.",
        "",
        "## Roles",
        "",
        "| Role | Responsibility |",
        "| --- | --- |",
    ]
    for role in Role:
        lines.append(f"| `{role.value}` | {ROLE_SUMMARY.get(role.value, '')} |")

    lines += [
        "",
        "## Jurisdiction model",
        "",
        "Codes are hierarchical and dash-separated, most general first:",
        "",
        "```",
        "IN                 national",
        "IN-HR              state",
        "IN-HR-GURUGRAM     district",
        "```",
        "",
        "| Role | Scope |",
        "| --- | --- |",
    ]
    for role in Role:
        if role in UNSCOPED_ROLES:
            scope = "All jurisdictions"
        elif role in HIERARCHY_ROLES:
            scope = "Its own code and everything beneath it"
        else:
            scope = "Its own code exactly"
        lines.append(f"| `{role.value}` | {scope} |")

    lines += [
        "",
        "A code beneath another must match on a whole segment: `IN-HR` covers",
        "`IN-HR-GURUGRAM` but not `IN-HRX-SOMEWHERE`. This is tested.",
        "",
        "Records with no jurisdiction yet, such as a newly submitted public complaint,",
        "are visible to anyone who can triage. Assignment sets the code and normal",
        "scoping applies from then on.",
        "",
        f"## Permission matrix ({len(list(Permission))} permissions)",
        "",
        "`Y` means the role holds the permission.",
        "",
    ]

    roles = list(Role)
    header = "| Permission | " + " | ".join(f"`{role.value}`" for role in roles) + " |"
    divider = "| --- | " + " | ".join("---" for _ in roles) + " |"
    lines += [header, divider]

    for permission in sorted(Permission, key=lambda item: item.value):
        cells = ["Y" if permission in ROLE_PERMISSIONS[role] else "·" for role in roles]
        lines.append(f"| `{permission.value}` | " + " | ".join(cells) + " |")

    lines += [
        "",
        "## Separation of duties",
        "",
        "- An inspector cannot record the final decision on an inspection.",
        "- A reviewer cannot read the audit trail; a controller can.",
        "- A rule administrator has no evidence permissions at all.",
        "- The author of a rule version cannot approve it, whatever their role.",
        "- No account can change its own role or deactivate itself.",
        "",
        "## What is not covered by permissions",
        "",
        "Holding a permission is necessary but never sufficient. State machine guards",
        "also apply: a reviewer with `inspection.decide` still cannot record a decision",
        "until every machine reading has been reviewed and the checks have been run.",
        "Those guards are declared in `app/domain/states.py` and enforced in",
        "`app/services/inspections.py`.",
        "",
    ]
    return "\n".join(lines)


def state_machines_document() -> str:
    lines: list[str] = [
        "# State machines",
        "",
        GENERATED_NOTE,
        "",
        "A state change is permitted only when all four hold:",
        "",
        "1. the caller's `expected_version` matches the stored version (optimistic lock);",
        "2. the pair of states is a declared edge below;",
        "3. the caller's role appears in that edge's roles;",
        "4. every guard on that edge passes.",
        "",
        "The interface shows why an unavailable action is unavailable, using the same",
        "guard evaluation, rather than hiding the control.",
        "",
    ]

    machines = [
        ("Inspection", INSPECTION_MACHINE),
        ("Complaint", COMPLAINT_MACHINE),
        ("Case", CASE_MACHINE),
    ]

    for title, machine in machines:
        lines += [
            f"## {title}",
            "",
            f"Initial state: `{machine.initial}`  ",
            f"States: {len(machine.states())}  ",
            f"Declared transitions: {len(machine.transitions)}",
            "",
            "| From | To | Action | Roles | Reason required | Guards |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for transition in sorted(machine.transitions, key=lambda item: (item.source, item.target)):
            roles = ", ".join(sorted(role.value for role in transition.roles))
            guards = ", ".join(f"`{guard}`" for guard in transition.guards) or "—"
            required = "yes" if transition.reason_required else "no"
            lines.append(
                f"| `{transition.source}` | `{transition.target}` | {transition.label} "
                f"| {roles} | {required} | {guards} |"
            )
        lines.append("")

    lines += [
        "## Guards",
        "",
        "| Guard | Passes when |",
        "| --- | --- |",
        "| `product_identified` | The inspection has a product with a brand and a name |",
        "| `has_evidence` | At least one evidence file has been uploaded |",
        "| `all_candidates_reviewed` | No machine reading is still pending review |",
        "| `all_checks_executed` | The checks have run since the last change and produced at least one finding |",
        "| `decision_recorded` | A decision and a reasoned note are stored |",
        "| `report_issued` | An issued report exists for the inspection |",
        "| `assignee_present` | An officer has been assigned to the complaint |",
        "| `inspection_linked` | An inspection has been opened from the complaint |",
        "| `notice_ready` | A notice has been prepared for the case |",
        "| `delivery_recorded` | Delivery of the notice has been recorded |",
        "",
        "An unrecognised guard name blocks the transition. Failing closed is the only",
        "safe behaviour when a precondition cannot be evaluated.",
        "",
        "## Frozen states",
        "",
        "Once an inspection reaches `report_issued`, `case_opened`, `closed` or",
        "`archived`, its evidence, readings and findings are read-only. An attempt to",
        "change them returns 409 `inspection_frozen`.",
        "",
        "An issued notice is frozen by a database trigger: its served text, hash,",
        "template version and issue time cannot change, though delivery, response and",
        "withdrawal can still be recorded against it.",
        "",
        "A report snapshot is frozen by a database trigger. Withdrawal and supersession",
        "are recorded in separate columns.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    target = Path(sys.argv[1] if len(sys.argv) > 1 else "docs")
    target.mkdir(parents=True, exist_ok=True)

    written: list[tuple[str, int]] = []
    for name, content in (
        ("PERMISSIONS.md", permissions_document()),
        ("STATE_MACHINES.md", state_machines_document()),
    ):
        path = target / name
        body = content.rstrip() + "\n"
        path.write_text(body, encoding="utf-8")
        written.append((name, len(body.splitlines())))

    stamp = datetime.now(UTC).strftime("%Y-%m-%d")
    for name, count in written:
        print(f"wrote {name} ({count} lines) on {stamp}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
