#!/bin/sh
# Regenerate requirements.lock.txt from requirements.txt inside a clean
# python:3.12-slim container. Run from the api/ directory:
#
#   docker run --rm -v "$PWD:/w" -w /w python:3.12-slim-bookworm sh scripts/lock.sh
#
set -eu

echo "resolving direct pins from requirements.txt"
pip install --quiet --no-cache-dir -r requirements.txt

{
  echo "# Generated by scripts/lock.sh. Do not edit by hand."
  echo "# Source: requirements.txt   Python: $(python -V 2>&1)"
  echo "# Regenerate: docker run --rm -v \"\$PWD:/w\" -w /w python:3.12-slim-bookworm sh scripts/lock.sh"
  pip freeze --exclude-editable
} > requirements.lock.txt

echo "wrote requirements.lock.txt with $(grep -c '==' requirements.lock.txt) pinned packages"
