"""initial schema

Revision ID: 0001_initial_schema
Revises:
Created: 2026-09-17 21:29:35.800585

Explicit DDL only. Do not import app.models here: a released migration must keep
working after the models change.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("jurisdiction_code", sa.String(length=64), nullable=False),
        sa.Column("jurisdiction_name", sa.String(length=160), nullable=False),
        sa.Column("designation", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_reason", sa.Text(), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret", sa.String(length=255), nullable=True),
        sa.Column("external_subject", sa.String(length=255), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('inspector', 'reviewer', 'controller', 'rule_admin', 'admin')",
            name=op.f("ck_users_users_role"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("external_subject", name=op.f("uq_users_external_subject")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index("ix_users_email_lower", "users", [sa.text("lower(email)")], unique=True)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(
        "ix_users_jurisdiction_active", "users", ["jurisdiction_code", "is_active"], unique=False
    )
    op.create_index(
        op.f("ix_users_jurisdiction_code"), "users", ["jurisdiction_code"], unique=False
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chain_key", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("entity_version", sa.Integer(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_role", sa.String(length=30), nullable=True),
        sa.Column("actor_email", sa.String(length=320), nullable=True),
        sa.Column("jurisdiction_code", sa.String(length=64), nullable=True),
        sa.Column("actor_is_public", sa.Boolean(), nullable=False),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_action_time", "audit_events", ["action", "recorded_at"], unique=False
    )
    op.create_index(
        "ix_audit_events_actor_time", "audit_events", ["actor_id", "recorded_at"], unique=False
    )
    op.create_index(
        "ix_audit_events_chain_sequence", "audit_events", ["chain_key", "sequence"], unique=True
    )
    op.create_index(
        "ix_audit_events_entity",
        "audit_events",
        ["entity_type", "entity_id", "recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_event_hash"), "audit_events", ["event_hash"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_recorded_at"), "audit_events", ["recorded_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("successful", sa.Boolean(), nullable=False),
        sa.Column("failure_reason", sa.String(length=60), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_login_attempts_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
    )
    op.create_index(
        op.f("ix_login_attempts_attempted_at"), "login_attempts", ["attempted_at"], unique=False
    )
    op.create_index(
        "ix_login_attempts_email_time", "login_attempts", ["email", "attempted_at"], unique=False
    )
    op.create_index(
        "ix_login_attempts_ip_time", "login_attempts", ["ip_address", "attempted_at"], unique=False
    )
    op.create_table(
        "notice_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("notice_type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("placeholders", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "notice_type IN ('show_cause', 'compliance_advisory', 'demand_for_information', 'hearing_notice')",
            name=op.f("ck_notice_templates_notice_templates_notice_type"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_notice_templates_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notice_templates")),
        sa.UniqueConstraint("code", "version", name="uq_notice_templates_code_version"),
    )
    op.create_index(op.f("ix_notice_templates_code"), "notice_templates", ["code"], unique=False)
    op.create_index(
        op.f("ix_notice_templates_created_at"), "notice_templates", ["created_at"], unique=False
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_by_id", sa.UUID(), nullable=True),
        sa.Column("request_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["issued_by_id"],
            ["users.id"],
            name=op.f("fk_password_reset_tokens_issued_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_reset_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_password_reset_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("brand", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("common_generic_name", sa.String(length=240), nullable=True),
        sa.Column("commodity_category", sa.String(length=120), nullable=False),
        sa.Column("is_food", sa.Boolean(), nullable=False),
        sa.Column("package_type", sa.String(length=30), nullable=False),
        sa.Column("quantity_kind", sa.String(length=20), nullable=True),
        sa.Column("declared_net_quantity", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("declared_net_quantity_unit", sa.String(length=16), nullable=True),
        sa.Column("net_quantity_base", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("is_imported", sa.Boolean(), nullable=False),
        sa.Column("country_of_origin", sa.String(length=80), nullable=True),
        sa.Column("is_multipiece", sa.Boolean(), nullable=False),
        sa.Column("pieces_per_package", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("merged_into_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "package_type IN ('pouch', 'carton', 'bottle', 'can', 'jar', 'sachet', 'tube', 'wrapper', 'box', 'sack', 'other')",
            name=op.f("ck_products_products_package_type"),
        ),
        sa.CheckConstraint(
            "quantity_kind IN ('weight', 'volume', 'length', 'area', 'count')",
            name=op.f("ck_products_products_quantity_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_products_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["products.id"],
            name=op.f("fk_products_merged_into_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_brand"), "products", ["brand"], unique=False)
    op.create_index("ix_products_brand_name", "products", ["brand", "name"], unique=False)
    op.create_index(
        op.f("ix_products_commodity_category"), "products", ["commodity_category"], unique=False
    )
    op.create_index(op.f("ix_products_created_at"), "products", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_products_merged_into_id"), "products", ["merged_into_id"], unique=False
    )
    op.create_index(
        "ix_products_search", "products", ["name", "brand", "commodity_category"], unique=False
    )
    op.create_table(
        "rule_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("record_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("citation", sa.String(length=300), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document_title", sa.String(length=300), nullable=True),
        sa.Column("gazette_reference", sa.String(length=240), nullable=True),
        sa.Column("source_retrieved_on", sa.Date(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("amends_rule_version_id", sa.UUID(), nullable=True),
        sa.Column("supersedes_rule_version_id", sa.UUID(), nullable=True),
        sa.Column("commodity_scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("package_scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quantity_kind", sa.String(length=20), nullable=True),
        sa.Column("quantity_min_base", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("quantity_max_base", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("applies_to_imported", sa.Boolean(), nullable=True),
        sa.Column("applies_to_ecommerce", sa.Boolean(), nullable=True),
        sa.Column("applies_to_multipiece", sa.Boolean(), nullable=True),
        sa.Column("exceptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("transition_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("required_inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("test_kind", sa.String(length=60), nullable=False),
        sa.Column("test_specification", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("plain_explanation", sa.Text(), nullable=False),
        sa.Column("interpretation_note", sa.Text(), nullable=False),
        sa.Column("uncertainty_note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approver_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_reason", sa.Text(), nullable=True),
        sa.Column("legal_authority_confirmed", sa.Boolean(), nullable=False),
        sa.Column("legal_authority_note", sa.Text(), nullable=True),
        sa.Column("test_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'under_review', 'changes_required', 'approved', 'active', 'superseded', 'withdrawn')",
            name=op.f("ck_rule_versions_rule_versions_status"),
        ),
        sa.ForeignKeyConstraint(
            ["amends_rule_version_id"],
            ["rule_versions.id"],
            name=op.f("fk_rule_versions_amends_rule_version_id_rule_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["users.id"],
            name=op.f("fk_rule_versions_approver_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_rule_versions_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_rule_versions_reviewer_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_rule_version_id"],
            ["rule_versions.id"],
            name=op.f("fk_rule_versions_supersedes_rule_version_id_rule_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_versions")),
        sa.UniqueConstraint("code", "version", name="uq_rule_versions_code_version"),
    )
    op.create_index(op.f("ix_rule_versions_code"), "rule_versions", ["code"], unique=False)
    op.create_index(
        "ix_rule_versions_code_status", "rule_versions", ["code", "status"], unique=False
    )
    op.create_index(
        op.f("ix_rule_versions_created_at"), "rule_versions", ["created_at"], unique=False
    )
    op.create_index(
        "ix_rule_versions_effective",
        "rule_versions",
        ["effective_from", "effective_to"],
        unique=False,
    )
    op.create_index(op.f("ix_rule_versions_status"), "rule_versions", ["status"], unique=False)
    op.create_table(
        "state_transitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("from_state", sa.String(length=40), nullable=True),
        sa.Column("to_state", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_role", sa.String(length=30), nullable=True),
        sa.Column("jurisdiction_code", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("entity_version", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_state_transitions_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_state_transitions")),
    )
    op.create_index(
        "ix_state_transitions_entity",
        "state_transitions",
        ["entity_type", "entity_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_state_transitions_occurred_at"), "state_transitions", ["occurred_at"], unique=False
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("rotated_to_id", sa.UUID(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=120), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rotated_to_id"],
            ["user_sessions.id"],
            name=op.f("fk_user_sessions_rotated_to_id_user_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("refresh_token_hash", name="uq_user_sessions_refresh_token_hash"),
    )
    op.create_index(
        op.f("ix_user_sessions_created_at"), "user_sessions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_sessions_expires_at"), "user_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_sessions_family_id"), "user_sessions", ["family_id"], unique=False
    )
    op.create_index(
        "ix_user_sessions_user_active", "user_sessions", ["user_id", "revoked_at"], unique=False
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "complaints",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("product_name", sa.String(length=240), nullable=False),
        sa.Column("brand", sa.String(length=160), nullable=True),
        sa.Column("barcode_value", sa.String(length=32), nullable=True),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("seller_name", sa.String(length=240), nullable=True),
        sa.Column("marketplace_name", sa.String(length=160), nullable=True),
        sa.Column("listing_url", sa.Text(), nullable=True),
        sa.Column("stated_mrp", sa.String(length=40), nullable=True),
        sa.Column("stated_price_paid", sa.String(length=40), nullable=True),
        sa.Column("location_text", sa.String(length=240), nullable=True),
        sa.Column("contact_name", sa.String(length=160), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("contact_phone", sa.String(length=40), nullable=True),
        sa.Column("contact_lookup_hash", sa.String(length=64), nullable=True),
        sa.Column("consent_to_contact", sa.Boolean(), nullable=False),
        sa.Column("consent_recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("privacy_notice_version", sa.String(length=20), nullable=True),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("priority_reason", sa.String(length=240), nullable=True),
        sa.Column("jurisdiction_code", sa.String(length=64), nullable=True),
        sa.Column("jurisdiction_name", sa.String(length=160), nullable=True),
        sa.Column("assigned_officer_id", sa.UUID(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("matched_product_id", sa.UUID(), nullable=True),
        sa.Column("duplicate_of_id", sa.UUID(), nullable=True),
        sa.Column("triage_note", sa.Text(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("closure_reason", sa.String(length=240), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_ip", postgresql.INET(), nullable=True),
        sa.Column("submitted_user_agent", sa.String(length=400), nullable=True),
        sa.Column("submission_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('missing_declaration', 'mrp_overcharge', 'incorrect_quantity', 'unreadable_label', 'misleading_claim', 'expired_or_date_issue', 'allergen_information', 'unsafe_product', 'other')",
            name=op.f("ck_complaints_complaints_category"),
        ),
        sa.CheckConstraint(
            "state IN ('received', 'triaged', 'duplicate', 'assigned', 'inspection_created', 'escalated', 'resolved', 'rejected', 'closed')",
            name=op.f("ck_complaints_complaints_state"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_officer_id"],
            ["users.id"],
            name=op.f("fk_complaints_assigned_officer_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_id"],
            ["complaints.id"],
            name=op.f("fk_complaints_duplicate_of_id_complaints"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["matched_product_id"],
            ["products.id"],
            name=op.f("fk_complaints_matched_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaints")),
        sa.UniqueConstraint("reference", name="uq_complaints_reference"),
    )
    op.create_index(
        op.f("ix_complaints_assigned_officer_id"),
        "complaints",
        ["assigned_officer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_complaints_barcode_value"), "complaints", ["barcode_value"], unique=False
    )
    op.create_index(op.f("ix_complaints_brand"), "complaints", ["brand"], unique=False)
    op.create_index(op.f("ix_complaints_category"), "complaints", ["category"], unique=False)
    op.create_index(
        op.f("ix_complaints_contact_email"), "complaints", ["contact_email"], unique=False
    )
    op.create_index(
        op.f("ix_complaints_contact_lookup_hash"),
        "complaints",
        ["contact_lookup_hash"],
        unique=False,
    )
    op.create_index(op.f("ix_complaints_created_at"), "complaints", ["created_at"], unique=False)
    op.create_index(
        "ix_complaints_jurisdiction", "complaints", ["jurisdiction_code", "state"], unique=False
    )
    op.create_index(
        op.f("ix_complaints_jurisdiction_code"), "complaints", ["jurisdiction_code"], unique=False
    )
    op.create_index(op.f("ix_complaints_priority"), "complaints", ["priority"], unique=False)
    op.create_index(
        op.f("ix_complaints_product_name"), "complaints", ["product_name"], unique=False
    )
    op.create_index(op.f("ix_complaints_reference"), "complaints", ["reference"], unique=False)
    op.create_index(op.f("ix_complaints_state"), "complaints", ["state"], unique=False)
    op.create_index(
        "ix_complaints_state_priority", "complaints", ["state", "priority"], unique=False
    )
    op.create_table(
        "product_identifiers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("scheme", sa.String(length=20), nullable=False),
        sa.Column("value", sa.String(length=32), nullable=False),
        sa.Column("check_digit_valid", sa.Boolean(), nullable=True),
        sa.Column("barcode_symbology", sa.String(length=40), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("observed_from", sa.Date(), nullable=True),
        sa.Column("observed_to", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("officer_confirmed", sa.Boolean(), nullable=False),
        sa.Column("recorded_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scheme IN ('gtin', 'ean8', 'upca', 'itf14', 'isbn', 'internal', 'other')",
            name=op.f("ck_product_identifiers_product_identifiers_scheme"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_identifiers_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_product_identifiers_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_identifiers")),
        sa.UniqueConstraint(
            "scheme", "value", "product_id", name="uq_product_identifiers_scheme_value_product_id"
        ),
    )
    op.create_index(
        op.f("ix_product_identifiers_created_at"),
        "product_identifiers",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_identifiers_product_id"),
        "product_identifiers",
        ["product_id"],
        unique=False,
    )
    op.create_index("ix_product_identifiers_value", "product_identifiers", ["value"], unique=False)
    op.create_table(
        "product_merge_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_product_id", sa.Uuid(), nullable=False),
        sa.Column("target_product_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("merged_by_id", sa.UUID(), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merged_by_id"],
            ["users.id"],
            name=op.f("fk_product_merge_records_merged_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_product_id"],
            ["products.id"],
            name=op.f("fk_product_merge_records_target_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_merge_records")),
    )
    op.create_index(
        op.f("ix_product_merge_records_source_product_id"),
        "product_merge_records",
        ["source_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_merge_records_target_product_id"),
        "product_merge_records",
        ["target_product_id"],
        unique=False,
    )
    op.create_table(
        "rule_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_version_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_role", sa.String(length=30), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('submitted', 'changes_required', 'approved', 'withdrawn', 'activated')",
            name=op.f("ck_rule_reviews_rule_reviews_decision"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_rule_reviews_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rule_version_id"],
            ["rule_versions.id"],
            name=op.f("fk_rule_reviews_rule_version_id_rule_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_reviews")),
    )
    op.create_index(
        "ix_rule_reviews_rule_version",
        "rule_reviews",
        ["rule_version_id", "recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rule_reviews_rule_version_id"), "rule_reviews", ["rule_version_id"], unique=False
    )
    op.create_table(
        "rule_test_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_version_id", sa.UUID(), nullable=False),
        sa.Column("scenarios", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("passed_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("all_passed", sa.Boolean(), nullable=False),
        sa.Column(
            "covered_scenario_kinds", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("run_by_id", sa.UUID(), nullable=True),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_version_id"],
            ["rule_versions.id"],
            name=op.f("fk_rule_test_runs_rule_version_id_rule_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_by_id"],
            ["users.id"],
            name=op.f("fk_rule_test_runs_run_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_test_runs")),
    )
    op.create_index(
        op.f("ix_rule_test_runs_rule_version_id"),
        "rule_test_runs",
        ["rule_version_id"],
        unique=False,
    )
    op.create_table(
        "inspections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("jurisdiction_code", sa.String(length=64), nullable=False),
        sa.Column("jurisdiction_name", sa.String(length=160), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("assigned_officer_id", sa.UUID(), nullable=True),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("inspection_date", sa.Date(), nullable=False),
        sa.Column("premises_name", sa.String(length=240), nullable=True),
        sa.Column("premises_address", sa.Text(), nullable=True),
        sa.Column("marketplace_name", sa.String(length=160), nullable=True),
        sa.Column("listing_url", sa.Text(), nullable=True),
        sa.Column("batch_reference", sa.String(length=60), nullable=True),
        sa.Column("complaint_id", sa.UUID(), nullable=True),
        sa.Column("parent_inspection_id", sa.UUID(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision", sa.String(length=40), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("decided_by_id", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checks_executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rules_evaluated_count", sa.Integer(), nullable=False),
        sa.Column("legal_hold", sa.Boolean(), nullable=False),
        sa.Column("retention_state", sa.String(length=30), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('field_inspection', 'retail_store', 'warehouse', 'complaint', 'ecommerce_listing', 'import_consignment', 'market_surveillance')",
            name=op.f("ck_inspections_inspections_source"),
        ),
        sa.CheckConstraint(
            "state IN ('draft', 'evidence_pending', 'processing', 'officer_review', 'reviewer_review', 'additional_evidence_required', 'compliant', 'violation_found', 'unable_to_determine', 'report_issued', 'case_opened', 'closed', 'archived')",
            name=op.f("ck_inspections_inspections_state"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_officer_id"],
            ["users.id"],
            name=op.f("fk_inspections_assigned_officer_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_inspections_complaint_id_complaints"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_inspections_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_id"],
            ["users.id"],
            name=op.f("fk_inspections_decided_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_inspection_id"],
            ["inspections.id"],
            name=op.f("fk_inspections_parent_inspection_id_inspections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inspections_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_inspections_reviewer_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspections")),
    )
    op.create_index(
        "ix_inspections_assigned", "inspections", ["assigned_officer_id", "state"], unique=False
    )
    op.create_index(
        op.f("ix_inspections_assigned_officer_id"),
        "inspections",
        ["assigned_officer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inspections_complaint_id"), "inspections", ["complaint_id"], unique=False
    )
    op.create_index(op.f("ix_inspections_created_at"), "inspections", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_inspections_created_by_id"), "inspections", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_inspections_inspection_date"), "inspections", ["inspection_date"], unique=False
    )
    op.create_index(
        op.f("ix_inspections_jurisdiction_code"), "inspections", ["jurisdiction_code"], unique=False
    )
    op.create_index(
        "ix_inspections_jurisdiction_state",
        "inspections",
        ["jurisdiction_code", "state"],
        unique=False,
    )
    op.create_index(op.f("ix_inspections_product_id"), "inspections", ["product_id"], unique=False)
    op.create_index(op.f("ix_inspections_reference"), "inspections", ["reference"], unique=True)
    op.create_index(
        op.f("ix_inspections_reviewer_id"), "inspections", ["reviewer_id"], unique=False
    )
    op.create_index(op.f("ix_inspections_state"), "inspections", ["state"], unique=False)
    op.create_index(
        "ix_inspections_state_updated", "inspections", ["state", "updated_at"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("complaint_id", sa.UUID(), nullable=True),
        sa.Column("face", sa.String(length=40), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("supplied_mime_type", sa.String(length=120), nullable=True),
        sa.Column("detected_mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("hash_algorithm", sa.String(length=20), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("original_width", sa.Integer(), nullable=True),
        sa.Column("original_height", sa.Integer(), nullable=True),
        sa.Column("stored_width", sa.Integer(), nullable=True),
        sa.Column("stored_height", sa.Integer(), nullable=True),
        sa.Column("storage_bucket", sa.String(length=120), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("storage_version_id", sa.String(length=120), nullable=True),
        sa.Column("storage_encryption", sa.String(length=40), nullable=True),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=True),
        sa.Column("uploaded_by_public", sa.Boolean(), nullable=False),
        sa.Column("upload_client_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("server_received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("upload_ip", postgresql.INET(), nullable=True),
        sa.Column("device_make", sa.String(length=80), nullable=True),
        sa.Column("device_model", sa.String(length=120), nullable=True),
        sa.Column("capture_latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("capture_longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("capture_accuracy_m", sa.Float(), nullable=True),
        sa.Column("exif_handling", sa.String(length=40), nullable=False),
        sa.Column("exif_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("analysis_state", sa.String(length=20), nullable=False),
        sa.Column("analysis_failure_reason", sa.Text(), nullable=True),
        sa.Column("quality", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quality_accepted_by_id", sa.UUID(), nullable=True),
        sa.Column("quality_override_reason", sa.Text(), nullable=True),
        sa.Column("barcodes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("malware_scan_state", sa.String(length=20), nullable=False),
        sa.Column("malware_scan_detail", sa.String(length=240), nullable=True),
        sa.Column("retention_state", sa.String(length=30), nullable=False),
        sa.Column("retain_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legal_hold", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "analysis_state IN ('pending', 'queued', 'running', 'completed', 'failed', 'skipped')",
            name=op.f("ck_evidence_evidence_analysis_state"),
        ),
        sa.CheckConstraint(
            "face IN ('principal_display_panel', 'declaration_panel', 'back_panel', 'side_panel_left', 'side_panel_right', 'top_panel', 'bottom_panel', 'barcode_area', 'mrp_close_up', 'net_quantity_close_up', 'date_marking_close_up', 'ingredients_panel', 'nutrition_panel', 'importer_label', 'other')",
            name=op.f("ck_evidence_evidence_face"),
        ),
        sa.CheckConstraint(
            "retention_state IN ('active', 'scheduled_for_deletion', 'deleted')",
            name=op.f("ck_evidence_evidence_retention_state"),
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_evidence_complaint_id_complaints"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_evidence_inspection_id_inspections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quality_accepted_by_id"],
            ["users.id"],
            name=op.f("fk_evidence_quality_accepted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_evidence_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint("storage_key", name="uq_evidence_storage_key"),
    )
    op.create_index(
        op.f("ix_evidence_analysis_state"), "evidence", ["analysis_state"], unique=False
    )
    op.create_index(op.f("ix_evidence_complaint_id"), "evidence", ["complaint_id"], unique=False)
    op.create_index(op.f("ix_evidence_created_at"), "evidence", ["created_at"], unique=False)
    op.create_index(
        "ix_evidence_inspection_face", "evidence", ["inspection_id", "face"], unique=False
    )
    op.create_index(op.f("ix_evidence_inspection_id"), "evidence", ["inspection_id"], unique=False)
    op.create_index("ix_evidence_sha256", "evidence", ["sha256"], unique=False)
    op.create_index(
        op.f("ix_evidence_uploaded_by_id"), "evidence", ["uploaded_by_id"], unique=False
    )
    op.create_table(
        "inspection_faces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("face", sa.String(length=40), nullable=False),
        sa.Column("capture_state", sa.String(length=40), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "capture_state IN ('required', 'captured', 'absent', 'not_applicable', 'unable_to_capture', 'additional_image_required')",
            name=op.f("ck_inspection_faces_inspection_faces_capture_state"),
        ),
        sa.CheckConstraint(
            "face IN ('principal_display_panel', 'declaration_panel', 'back_panel', 'side_panel_left', 'side_panel_right', 'top_panel', 'bottom_panel', 'barcode_area', 'mrp_close_up', 'net_quantity_close_up', 'date_marking_close_up', 'ingredients_panel', 'nutrition_panel', 'importer_label', 'other')",
            name=op.f("ck_inspection_faces_inspection_faces_face"),
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_inspection_faces_inspection_id_inspections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_inspection_faces_updated_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspection_faces")),
        sa.UniqueConstraint("inspection_id", "face", name="uq_inspection_faces_inspection_id_face"),
    )
    op.create_index(
        op.f("ix_inspection_faces_created_at"), "inspection_faces", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_inspection_faces_inspection_id"),
        "inspection_faces",
        ["inspection_id"],
        unique=False,
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=40), nullable=False),
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("snapshot_algorithm", sa.String(length=60), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("issued_by_id", sa.UUID(), nullable=True),
        sa.Column("issuing_workspace", sa.String(length=200), nullable=False),
        sa.Column("jurisdiction_code", sa.String(length=64), nullable=False),
        sa.Column("signature_status", sa.String(length=30), nullable=False),
        sa.Column("signature_value", sa.Text(), nullable=True),
        sa.Column("signature_key_id", sa.String(length=80), nullable=True),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_code", sa.String(length=24), nullable=False),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_by_id", sa.UUID(), nullable=True),
        sa.Column("withdrawn_reason", sa.Text(), nullable=True),
        sa.Column("superseded_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('issued', 'withdrawn', 'superseded')", name=op.f("ck_reports_reports_state")
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_reports_inspection_id_inspections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_id"],
            ["users.id"],
            name=op.f("fk_reports_issued_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["reports.id"],
            name=op.f("fk_reports_superseded_by_id_reports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["withdrawn_by_id"],
            ["users.id"],
            name=op.f("fk_reports_withdrawn_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("inspection_id", "revision", name="uq_reports_inspection_id_revision"),
        sa.UniqueConstraint("reference", name="uq_reports_reference"),
        sa.UniqueConstraint("verification_code", name=op.f("uq_reports_verification_code")),
    )
    op.create_index(op.f("ix_reports_created_at"), "reports", ["created_at"], unique=False)
    op.create_index(op.f("ix_reports_inspection_id"), "reports", ["inspection_id"], unique=False)
    op.create_index(op.f("ix_reports_issued_at"), "reports", ["issued_at"], unique=False)
    op.create_index(
        op.f("ix_reports_jurisdiction_code"), "reports", ["jurisdiction_code"], unique=False
    )
    op.create_index(op.f("ix_reports_reference"), "reports", ["reference"], unique=False)
    op.create_index("ix_reports_snapshot_sha256", "reports", ["snapshot_sha256"], unique=False)
    op.create_index(op.f("ix_reports_state"), "reports", ["state"], unique=False)
    op.create_table(
        "analysis_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_type", sa.String(length=40), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=True),
        sa.Column("inspection_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=60), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("queue_message_id", sa.String(length=120), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_analysis_jobs_analysis_jobs_state"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_analysis_jobs_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_analysis_jobs_inspection_id_inspections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
            name=op.f("fk_analysis_jobs_requested_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_jobs")),
        sa.UniqueConstraint("idempotency_key", name="uq_analysis_jobs_idempotency_key"),
    )
    op.create_index(
        op.f("ix_analysis_jobs_created_at"), "analysis_jobs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_jobs_evidence_id"), "analysis_jobs", ["evidence_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_jobs_inspection_id"), "analysis_jobs", ["inspection_id"], unique=False
    )
    op.create_index(op.f("ix_analysis_jobs_job_type"), "analysis_jobs", ["job_type"], unique=False)
    op.create_index(op.f("ix_analysis_jobs_state"), "analysis_jobs", ["state"], unique=False)
    op.create_index(
        "ix_analysis_jobs_state_created", "analysis_jobs", ["state", "created_at"], unique=False
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=True),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("jurisdiction_code", sa.String(length=64), nullable=False),
        sa.Column("jurisdiction_name", sa.String(length=160), nullable=False),
        sa.Column("respondent_name", sa.String(length=240), nullable=False),
        sa.Column("respondent_role", sa.String(length=30), nullable=True),
        sa.Column("respondent_address", sa.Text(), nullable=True),
        sa.Column("respondent_email", sa.String(length=320), nullable=True),
        sa.Column("respondent_phone", sa.String(length=40), nullable=True),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("legal_basis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rule_version_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("opened_by_id", sa.UUID(), nullable=True),
        sa.Column("assigned_officer_id", sa.UUID(), nullable=True),
        sa.Column("follow_up_inspection_id", sa.UUID(), nullable=True),
        sa.Column("outcome", sa.String(length=60), nullable=True),
        sa.Column("outcome_note", sa.Text(), nullable=True),
        sa.Column("closure_reason", sa.String(length=240), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('draft', 'notice_issued', 'awaiting_response', 'response_received', 'hearing_scheduled', 'under_consideration', 'follow_up_inspection', 'resolved', 'withdrawn', 'closed')",
            name=op.f("ck_cases_cases_state"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_officer_id"],
            ["users.id"],
            name=op.f("fk_cases_assigned_officer_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["follow_up_inspection_id"],
            ["inspections.id"],
            name=op.f("fk_cases_follow_up_inspection_id_inspections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_cases_inspection_id_inspections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_id"],
            ["users.id"],
            name=op.f("fk_cases_opened_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_cases_report_id_reports"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
        sa.UniqueConstraint("reference", name="uq_cases_reference"),
    )
    op.create_index(
        op.f("ix_cases_assigned_officer_id"), "cases", ["assigned_officer_id"], unique=False
    )
    op.create_index(op.f("ix_cases_created_at"), "cases", ["created_at"], unique=False)
    op.create_index(op.f("ix_cases_inspection_id"), "cases", ["inspection_id"], unique=False)
    op.create_index(
        op.f("ix_cases_jurisdiction_code"), "cases", ["jurisdiction_code"], unique=False
    )
    op.create_index(
        "ix_cases_jurisdiction_state", "cases", ["jurisdiction_code", "state"], unique=False
    )
    op.create_index(op.f("ix_cases_reference"), "cases", ["reference"], unique=False)
    op.create_index(op.f("ix_cases_state"), "cases", ["state"], unique=False)
    op.create_table(
        "complaint_attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("complaint_id", sa.UUID(), nullable=False),
        sa.Column("attachment_kind", sa.String(length=30), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("detected_mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_bucket", sa.String(length=120), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("promoted_evidence_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attachment_kind IN ('package_image', 'purchase_proof', 'other')",
            name=op.f("ck_complaint_attachments_complaint_attachments_attachment_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
            name=op.f("fk_complaint_attachments_complaint_id_complaints"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["promoted_evidence_id"],
            ["evidence.id"],
            name=op.f("fk_complaint_attachments_promoted_evidence_id_evidence"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_attachments")),
        sa.UniqueConstraint("storage_key", name="uq_complaint_attachments_storage_key"),
    )
    op.create_index(
        op.f("ix_complaint_attachments_complaint_id"),
        "complaint_attachments",
        ["complaint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_complaint_attachments_created_at"),
        "complaint_attachments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_complaint_attachments_sha256"), "complaint_attachments", ["sha256"], unique=False
    )
    op.create_table(
        "evidence_derivatives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("storage_bucket", sa.String(length=120), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("transform", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generator_version", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('original', 'thumbnail', 'ocr_input', 'annotated', 'report_image')",
            name=op.f("ck_evidence_derivatives_evidence_derivatives_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_evidence_derivatives_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_derivatives")),
        sa.UniqueConstraint("evidence_id", "kind", name="uq_evidence_derivatives_evidence_id_kind"),
    )
    op.create_index(
        op.f("ix_evidence_derivatives_created_at"),
        "evidence_derivatives",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_derivatives_evidence_id"),
        "evidence_derivatives",
        ["evidence_id"],
        unique=False,
    )
    op.create_table(
        "ocr_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("profile", sa.String(length=40), nullable=False),
        sa.Column("engine", sa.String(length=40), nullable=False),
        sa.Column("engine_version", sa.String(length=40), nullable=True),
        sa.Column("languages", sa.String(length=40), nullable=False),
        sa.Column("detected_script", sa.String(length=40), nullable=True),
        sa.Column("orientation_applied_degrees", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("words", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mean_confidence", sa.Float(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_ocr_results_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_results")),
        sa.UniqueConstraint("evidence_id", "profile", name="uq_ocr_results_evidence_id_profile"),
    )
    op.create_index(op.f("ix_ocr_results_created_at"), "ocr_results", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_ocr_results_evidence_id"), "ocr_results", ["evidence_id"], unique=False
    )
    op.create_table(
        "report_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column("storage_bucket", sa.String(length=120), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("renderer_version", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "format IN ('pdf', 'docx')", name=op.f("ck_report_documents_report_documents_format")
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_report_documents_report_id_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_documents")),
        sa.UniqueConstraint("report_id", "format", name="uq_report_documents_report_id_format"),
    )
    op.create_index(
        op.f("ix_report_documents_created_at"), "report_documents", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_report_documents_report_id"), "report_documents", ["report_id"], unique=False
    )
    op.create_table(
        "responsible_parties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("party_role", sa.String(length=20), nullable=False),
        sa.Column("legal_name", sa.String(length=240), nullable=False),
        sa.Column("address_line", sa.Text(), nullable=True),
        sa.Column("locality", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=80), nullable=True),
        sa.Column("pin_code", sa.String(length=12), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("consumer_care_name", sa.String(length=160), nullable=True),
        sa.Column("consumer_care_email", sa.String(length=320), nullable=True),
        sa.Column("consumer_care_phone", sa.String(length=40), nullable=True),
        sa.Column("observed_from", sa.Date(), nullable=True),
        sa.Column("observed_to", sa.Date(), nullable=True),
        sa.Column("source_evidence_id", sa.UUID(), nullable=True),
        sa.Column("recorded_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "party_role IN ('manufacturer', 'packer', 'importer', 'marketer', 'brand_owner')",
            name=op.f("ck_responsible_parties_responsible_parties_party_role"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_responsible_parties_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_responsible_parties_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_evidence_id"],
            ["evidence.id"],
            name=op.f("fk_responsible_parties_source_evidence_id_evidence"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_responsible_parties")),
    )
    op.create_index(
        op.f("ix_responsible_parties_created_at"),
        "responsible_parties",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_responsible_parties_product_id"),
        "responsible_parties",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        "ix_responsible_parties_product_role",
        "responsible_parties",
        ["product_id", "party_role"],
        unique=False,
    )
    op.create_table(
        "case_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_case_events_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_events_case_id_cases"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_events")),
    )
    op.create_index(op.f("ix_case_events_case_id"), "case_events", ["case_id"], unique=False)
    op.create_index(
        "ix_case_events_case_time", "case_events", ["case_id", "occurred_at"], unique=False
    )
    op.create_table(
        "declaration_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=True),
        sa.Column("ocr_result_id", sa.UUID(), nullable=True),
        sa.Column("declaration_type", sa.String(length=40), nullable=False),
        sa.Column("machine_state", sa.String(length=30), nullable=False),
        sa.Column("matched_text", sa.Text(), nullable=True),
        sa.Column("context_text", sa.Text(), nullable=True),
        sa.Column("normalised_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("numeric_value", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("region", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("text_height_px", sa.Float(), nullable=True),
        sa.Column("machine_confidence", sa.Float(), nullable=True),
        sa.Column("parser_name", sa.String(length=60), nullable=False),
        sa.Column("parser_version", sa.String(length=20), nullable=False),
        sa.Column("machine_explanation", sa.Text(), nullable=True),
        sa.Column("review_state", sa.String(length=30), nullable=False),
        sa.Column("corrected_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corrected_numeric_value", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("corrected_unit", sa.String(length=16), nullable=True),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "declaration_type IN ('mrp', 'net_quantity', 'unit_sale_price', 'retail_sale_price_label', 'manufacturer', 'packer', 'importer', 'marketer', 'responsible_party_address', 'consumer_care_email', 'consumer_care_phone', 'consumer_care_name', 'country_of_origin', 'common_generic_name', 'date_of_manufacture', 'date_of_packing', 'date_of_import', 'best_before', 'batch_number', 'lot_number', 'ingredients', 'nutrition', 'allergen_statement', 'veg_nonveg_mark', 'fssai_licence')",
            name=op.f("ck_declaration_candidates_declaration_candidates_declaration_type"),
        ),
        sa.CheckConstraint(
            "machine_state IN ('located', 'not_detected', 'unreadable', 'ambiguous', 'incomplete_evidence', 'processing_failed')",
            name=op.f("ck_declaration_candidates_declaration_candidates_machine_state"),
        ),
        sa.CheckConstraint(
            "review_state IN ('pending', 'confirmed', 'rejected', 'corrected', 'not_applicable')",
            name=op.f("ck_declaration_candidates_declaration_candidates_review_state"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_declaration_candidates_evidence_id_evidence"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_declaration_candidates_inspection_id_inspections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_result_id"],
            ["ocr_results.id"],
            name=op.f("fk_declaration_candidates_ocr_result_id_ocr_results"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_declaration_candidates_reviewed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_declaration_candidates")),
    )
    op.create_index(
        op.f("ix_declaration_candidates_created_at"),
        "declaration_candidates",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_declaration_candidates_evidence_id"),
        "declaration_candidates",
        ["evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_declaration_candidates_inspection_id"),
        "declaration_candidates",
        ["inspection_id"],
        unique=False,
    )
    op.create_index(
        "ix_declaration_candidates_inspection_type",
        "declaration_candidates",
        ["inspection_id", "declaration_type"],
        unique=False,
    )
    op.create_index(
        "ix_declaration_candidates_review",
        "declaration_candidates",
        ["inspection_id", "review_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_declaration_candidates_review_state"),
        "declaration_candidates",
        ["review_state"],
        unique=False,
    )
    op.create_table(
        "notices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("notice_type", sa.String(length=40), nullable=False),
        sa.Column("template_code", sa.String(length=60), nullable=False),
        sa.Column("template_version", sa.Integer(), nullable=False),
        sa.Column("rendered_body", sa.Text(), nullable=False),
        sa.Column("rendered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("body_sha256", sa.String(length=64), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_by_id", sa.UUID(), nullable=True),
        sa.Column("is_frozen", sa.Boolean(), nullable=False),
        sa.Column("delivery_method", sa.String(length=30), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_proof_reference", sa.String(length=160), nullable=True),
        sa.Column("delivery_note", sa.Text(), nullable=True),
        sa.Column("response_due_on", sa.Date(), nullable=True),
        sa.Column("reminder_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_summary", sa.Text(), nullable=True),
        sa.Column("response_storage_key", sa.Text(), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_method IN ('hand_delivery', 'registered_post', 'speed_post', 'email', 'courier', 'public_notice')",
            name=op.f("ck_notices_notices_delivery_method"),
        ),
        sa.CheckConstraint(
            "notice_type IN ('show_cause', 'compliance_advisory', 'demand_for_information', 'hearing_notice')",
            name=op.f("ck_notices_notices_notice_type"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_notices_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_id"],
            ["users.id"],
            name=op.f("fk_notices_issued_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notices")),
        sa.UniqueConstraint("reference", name="uq_notices_reference"),
    )
    op.create_index(op.f("ix_notices_case_id"), "notices", ["case_id"], unique=False)
    op.create_index(op.f("ix_notices_created_at"), "notices", ["created_at"], unique=False)
    op.create_index(op.f("ix_notices_reference"), "notices", ["reference"], unique=False)
    op.create_index(
        op.f("ix_notices_response_due_on"), "notices", ["response_due_on"], unique=False
    )
    op.create_table(
        "candidate_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("previous_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_kind", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_role", sa.String(length=30), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_candidate_revisions_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["declaration_candidates.id"],
            name=op.f("fk_candidate_revisions_candidate_id_declaration_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_revisions")),
    )
    op.create_index(
        "ix_candidate_revisions_candidate",
        "candidate_revisions",
        ["candidate_id", "recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_revisions_candidate_id"),
        "candidate_revisions",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("rule_version_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=True),
        sa.Column("declaration_type", sa.String(length=40), nullable=True),
        sa.Column("outcome", sa.String(length=40), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("selection_reason", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("test_inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("calculation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_value", sa.String(length=240), nullable=True),
        sa.Column("observed_value", sa.String(length=240), nullable=True),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("officer_outcome", sa.String(length=40), nullable=True),
        sa.Column("officer_note", sa.Text(), nullable=True),
        sa.Column("officer_id", sa.UUID(), nullable=True),
        sa.Column("officer_recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("superseded_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('compliant', 'non_compliant', 'unable_to_determine', 'not_applicable', 'additional_evidence_required')",
            name=op.f("ck_findings_findings_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["declaration_candidates.id"],
            name=op.f("fk_findings_candidate_id_declaration_candidates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_findings_inspection_id_inspections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["users.id"],
            name=op.f("fk_findings_officer_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rule_version_id"],
            ["rule_versions.id"],
            name=op.f("fk_findings_rule_version_id_rule_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["findings.id"],
            name=op.f("fk_findings_superseded_by_id_findings"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_index(op.f("ix_findings_created_at"), "findings", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_findings_declaration_type"), "findings", ["declaration_type"], unique=False
    )
    op.create_index(op.f("ix_findings_inspection_id"), "findings", ["inspection_id"], unique=False)
    op.create_index(
        "ix_findings_inspection_outcome", "findings", ["inspection_id", "outcome"], unique=False
    )
    op.create_index(op.f("ix_findings_is_current"), "findings", ["is_current"], unique=False)
    op.create_index(op.f("ix_findings_outcome"), "findings", ["outcome"], unique=False)
    op.create_index("ix_findings_rule_version", "findings", ["rule_version_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_findings_rule_version", table_name="findings")
    op.drop_index(op.f("ix_findings_outcome"), table_name="findings")
    op.drop_index(op.f("ix_findings_is_current"), table_name="findings")
    op.drop_index("ix_findings_inspection_outcome", table_name="findings")
    op.drop_index(op.f("ix_findings_inspection_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_declaration_type"), table_name="findings")
    op.drop_index(op.f("ix_findings_created_at"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_candidate_revisions_candidate_id"), table_name="candidate_revisions")
    op.drop_index("ix_candidate_revisions_candidate", table_name="candidate_revisions")
    op.drop_table("candidate_revisions")
    op.drop_index(op.f("ix_notices_response_due_on"), table_name="notices")
    op.drop_index(op.f("ix_notices_reference"), table_name="notices")
    op.drop_index(op.f("ix_notices_created_at"), table_name="notices")
    op.drop_index(op.f("ix_notices_case_id"), table_name="notices")
    op.drop_table("notices")
    op.drop_index(
        op.f("ix_declaration_candidates_review_state"), table_name="declaration_candidates"
    )
    op.drop_index("ix_declaration_candidates_review", table_name="declaration_candidates")
    op.drop_index("ix_declaration_candidates_inspection_type", table_name="declaration_candidates")
    op.drop_index(
        op.f("ix_declaration_candidates_inspection_id"), table_name="declaration_candidates"
    )
    op.drop_index(
        op.f("ix_declaration_candidates_evidence_id"), table_name="declaration_candidates"
    )
    op.drop_index(op.f("ix_declaration_candidates_created_at"), table_name="declaration_candidates")
    op.drop_table("declaration_candidates")
    op.drop_index("ix_case_events_case_time", table_name="case_events")
    op.drop_index(op.f("ix_case_events_case_id"), table_name="case_events")
    op.drop_table("case_events")
    op.drop_index("ix_responsible_parties_product_role", table_name="responsible_parties")
    op.drop_index(op.f("ix_responsible_parties_product_id"), table_name="responsible_parties")
    op.drop_index(op.f("ix_responsible_parties_created_at"), table_name="responsible_parties")
    op.drop_table("responsible_parties")
    op.drop_index(op.f("ix_report_documents_report_id"), table_name="report_documents")
    op.drop_index(op.f("ix_report_documents_created_at"), table_name="report_documents")
    op.drop_table("report_documents")
    op.drop_index(op.f("ix_ocr_results_evidence_id"), table_name="ocr_results")
    op.drop_index(op.f("ix_ocr_results_created_at"), table_name="ocr_results")
    op.drop_table("ocr_results")
    op.drop_index(op.f("ix_evidence_derivatives_evidence_id"), table_name="evidence_derivatives")
    op.drop_index(op.f("ix_evidence_derivatives_created_at"), table_name="evidence_derivatives")
    op.drop_table("evidence_derivatives")
    op.drop_index(op.f("ix_complaint_attachments_sha256"), table_name="complaint_attachments")
    op.drop_index(op.f("ix_complaint_attachments_created_at"), table_name="complaint_attachments")
    op.drop_index(op.f("ix_complaint_attachments_complaint_id"), table_name="complaint_attachments")
    op.drop_table("complaint_attachments")
    op.drop_index(op.f("ix_cases_state"), table_name="cases")
    op.drop_index(op.f("ix_cases_reference"), table_name="cases")
    op.drop_index("ix_cases_jurisdiction_state", table_name="cases")
    op.drop_index(op.f("ix_cases_jurisdiction_code"), table_name="cases")
    op.drop_index(op.f("ix_cases_inspection_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_created_at"), table_name="cases")
    op.drop_index(op.f("ix_cases_assigned_officer_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_index("ix_analysis_jobs_state_created", table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_state"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_job_type"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_inspection_id"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_evidence_id"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_created_at"), table_name="analysis_jobs")
    op.drop_table("analysis_jobs")
    op.drop_index(op.f("ix_reports_state"), table_name="reports")
    op.drop_index("ix_reports_snapshot_sha256", table_name="reports")
    op.drop_index(op.f("ix_reports_reference"), table_name="reports")
    op.drop_index(op.f("ix_reports_jurisdiction_code"), table_name="reports")
    op.drop_index(op.f("ix_reports_issued_at"), table_name="reports")
    op.drop_index(op.f("ix_reports_inspection_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_created_at"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_inspection_faces_inspection_id"), table_name="inspection_faces")
    op.drop_index(op.f("ix_inspection_faces_created_at"), table_name="inspection_faces")
    op.drop_table("inspection_faces")
    op.drop_index(op.f("ix_evidence_uploaded_by_id"), table_name="evidence")
    op.drop_index("ix_evidence_sha256", table_name="evidence")
    op.drop_index(op.f("ix_evidence_inspection_id"), table_name="evidence")
    op.drop_index("ix_evidence_inspection_face", table_name="evidence")
    op.drop_index(op.f("ix_evidence_created_at"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_complaint_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_analysis_state"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index("ix_inspections_state_updated", table_name="inspections")
    op.drop_index(op.f("ix_inspections_state"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_reviewer_id"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_reference"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_product_id"), table_name="inspections")
    op.drop_index("ix_inspections_jurisdiction_state", table_name="inspections")
    op.drop_index(op.f("ix_inspections_jurisdiction_code"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_inspection_date"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_created_by_id"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_created_at"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_complaint_id"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_assigned_officer_id"), table_name="inspections")
    op.drop_index("ix_inspections_assigned", table_name="inspections")
    op.drop_table("inspections")
    op.drop_index(op.f("ix_rule_test_runs_rule_version_id"), table_name="rule_test_runs")
    op.drop_table("rule_test_runs")
    op.drop_index(op.f("ix_rule_reviews_rule_version_id"), table_name="rule_reviews")
    op.drop_index("ix_rule_reviews_rule_version", table_name="rule_reviews")
    op.drop_table("rule_reviews")
    op.drop_index(
        op.f("ix_product_merge_records_target_product_id"), table_name="product_merge_records"
    )
    op.drop_index(
        op.f("ix_product_merge_records_source_product_id"), table_name="product_merge_records"
    )
    op.drop_table("product_merge_records")
    op.drop_index("ix_product_identifiers_value", table_name="product_identifiers")
    op.drop_index(op.f("ix_product_identifiers_product_id"), table_name="product_identifiers")
    op.drop_index(op.f("ix_product_identifiers_created_at"), table_name="product_identifiers")
    op.drop_table("product_identifiers")
    op.drop_index("ix_complaints_state_priority", table_name="complaints")
    op.drop_index(op.f("ix_complaints_state"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_reference"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_product_name"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_priority"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_jurisdiction_code"), table_name="complaints")
    op.drop_index("ix_complaints_jurisdiction", table_name="complaints")
    op.drop_index(op.f("ix_complaints_created_at"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_contact_lookup_hash"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_contact_email"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_category"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_brand"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_barcode_value"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_assigned_officer_id"), table_name="complaints")
    op.drop_table("complaints")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index("ix_user_sessions_user_active", table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_family_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_expires_at"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_created_at"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_state_transitions_occurred_at"), table_name="state_transitions")
    op.drop_index("ix_state_transitions_entity", table_name="state_transitions")
    op.drop_table("state_transitions")
    op.drop_index(op.f("ix_rule_versions_status"), table_name="rule_versions")
    op.drop_index("ix_rule_versions_effective", table_name="rule_versions")
    op.drop_index(op.f("ix_rule_versions_created_at"), table_name="rule_versions")
    op.drop_index("ix_rule_versions_code_status", table_name="rule_versions")
    op.drop_index(op.f("ix_rule_versions_code"), table_name="rule_versions")
    op.drop_table("rule_versions")
    op.drop_index("ix_products_search", table_name="products")
    op.drop_index(op.f("ix_products_merged_into_id"), table_name="products")
    op.drop_index(op.f("ix_products_created_at"), table_name="products")
    op.drop_index(op.f("ix_products_commodity_category"), table_name="products")
    op.drop_index("ix_products_brand_name", table_name="products")
    op.drop_index(op.f("ix_products_brand"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_notice_templates_created_at"), table_name="notice_templates")
    op.drop_index(op.f("ix_notice_templates_code"), table_name="notice_templates")
    op.drop_table("notice_templates")
    op.drop_index("ix_login_attempts_ip_time", table_name="login_attempts")
    op.drop_index("ix_login_attempts_email_time", table_name="login_attempts")
    op.drop_index(op.f("ix_login_attempts_attempted_at"), table_name="login_attempts")
    op.drop_table("login_attempts")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_recorded_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_hash"), table_name="audit_events")
    op.drop_index("ix_audit_events_entity", table_name="audit_events")
    op.drop_index("ix_audit_events_chain_sequence", table_name="audit_events")
    op.drop_index("ix_audit_events_actor_time", table_name="audit_events")
    op.drop_index("ix_audit_events_action_time", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_jurisdiction_code"), table_name="users")
    op.drop_index("ix_users_jurisdiction_active", table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index("ix_users_email_lower", table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
